In [1]:
# import libraries
import numpy as np
import imageio
from PIL import Image
import os

In [2]:
def image_to_matrix(image_path):
    # Open the image
    img = Image.open(image_path)
    
    # Convert Image to gray-scale
    img = img.convert("L")
    
    # Convert to a binary matrix
    width , height = img.size
    
    matrix = [[0 if img.getpixel((x,y))== 255 else 1 for x in range(width)]for y in range(height)]
    return np.array(matrix)

In [3]:
def matrix_to_image(matrix, counter, file_name = None):
    scale = 300 // matrix.shape[0]
    
    matrix = np.repeat(matrix, scale, axis=1)
    matrix = np.repeat(matrix, scale, axis=0)
    
    height, width = len(matrix), len(matrix[0])
    
    img = Image.new("RGB", (width, height))
    
    for y in range(height):
        for x in range(width):
            if matrix[y][x] == 1:
                img.putpixel((x,y), (0,0,0))
            elif matrix[y][x] == 0:
                img.putpixel((x,y), (255,255,255))
            elif matrix[y][x] == -2:
                img.putpixel((x,y), (0,0,255))
            
            else:
                img.putpixel((x,y),(0,255,0))
    
    img.save(f"{file_name}/{counter}.png", quality=99)
                

In [4]:
def matrix_to_image_GS(matrix, output_path):
    # Determine the size of the image
    height = len(matrix)
    width = len(matrix[0])
    
    # Create a new blank image
    img = Image.new('RGB', (width, height), color='white')
    
    # Set pixel values based on the binary matrix
    for y in range(height):
        for x in range(width):
            # If matrix value is 1, set pixel to black
            if matrix[y][x] == 1:
                img.putpixel((x, y), (0, 0, 0))
            # Otherwise, set pixel to white
            else:
                img.putpixel((x, y), (255, 255, 255))
    
    # Save the image to the output path
    img.save(output_path)


In [5]:

def step(i, j, fn, matrix= None, deep_path = [], final_path=[] , end_point= (0,0)):
    global counter
    
    if matrix[end_point]>0:
        return
    
    if i<0 or i>=matrix.shape[0] or j<0 or j>=matrix.shape[1]:
        return
    
    if (i,j) in deep_path or matrix[(i,j)]>0:
        return
    
    deep_path.append((i,j))
    final_path.append((i,j))
    counter += 1
    matrix[(i,j)] = counter
    matrix_to_image(matrix, counter, file_name = fn)
    
    if (i,j) == end_point:
        print(f"This is the deep path: {deep_path}\n")
        print(f"\nThis is the final path: {final_path}")
        return
    
    
    else:
        step(i + 1, j, fn, matrix, deep_path, final_path, end_point)
        step(i, j - 1, fn, matrix, deep_path, final_path, end_point)
        step(i, j + 1, fn, matrix, deep_path, final_path, end_point)
        step(i - 1, j, fn, matrix, deep_path, final_path, end_point)
        if (i,j) in deep_path or matrix[(i,j)] > 0:
            matrix[(i,j)]=-2
            final_path.pop()
            return
         

In [6]:
image_path = 'Maze1.png'
maze1 = image_to_matrix(image_path)
print(maze1)

[[1 1 1 1 0 1 1 1 1 1 1 1]
 [1 0 1 0 0 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 0 1 0 1 0 1]
 [1 0 0 1 0 0 0 1 0 1 0 1]
 [1 1 0 1 0 1 1 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 1 0 0 0 0 0 0 1]
 [1 1 1 0 1 0 1 1 1 1 0 1]
 [1 0 0 0 1 0 1 0 0 0 0 1]
 [1 0 1 1 1 0 1 0 1 1 0 1]
 [1 0 0 0 0 0 1 0 1 0 0 1]
 [1 1 1 1 1 1 1 0 1 1 1 1]]


In [7]:
image_name2 = os.path.splitext(os.path.basename(image_path))[0]
image_name2

'Maze1'

In [8]:
try:
   os.makedirs(image_name2)
except FileExistsError:
   # directory already exists
   pass

In [9]:
start = (0,4)
end_point = (12,7)

counter = 1
step(start[0],start[1],fn=image_name2, matrix = maze1 , end_point = end_point)
print()
print(maze1)

This is the deep path: [(0, 4), (1, 4), (1, 3), (1, 5), (1, 6), (2, 6), (3, 6), (3, 5), (3, 4), (4, 4), (5, 4), (5, 3), (5, 2), (5, 1), (6, 1), (7, 1), (7, 2), (7, 3), (8, 3), (9, 3), (9, 2), (9, 1), (10, 1), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (10, 5), (9, 5), (8, 5), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (8, 10), (9, 10), (10, 10), (11, 10), (11, 9), (9, 9), (9, 8), (9, 7), (10, 7), (11, 7), (12, 7)]


This is the final path: [(0, 4), (1, 4), (1, 5), (1, 6), (2, 6), (3, 6), (3, 5), (3, 4), (4, 4), (5, 4), (5, 3), (5, 2), (5, 1), (6, 1), (7, 1), (7, 2), (7, 3), (8, 3), (9, 3), (9, 2), (9, 1), (10, 1), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (10, 5), (9, 5), (8, 5), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (8, 10), (9, 10), (9, 9), (9, 8), (9, 7), (10, 7), (11, 7), (12, 7)]

[[ 1  1  1  1 -2  1  1  1  1  1  1  1]
 [ 1  0  1 -2 -2 -2 -2  1  0  0  0  1]
 [ 1  0  1  1  1  1 -2  1  0  1  0  1]
 [ 1  0  0  1 -2 -2 -2  1  0  1  0  1]
 [ 1  1  0  1 -2  1  1  1

In [10]:
import warnings
warnings.simplefilter("ignore")

images = [imageio.imread(f'{image_name2}/{i}.png') for i in range(2,counter+1)]
imageio.mimsave(f'{image_name2}/path.gif', images, duration =5.5)

In [11]:
maze2 = np.array([
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                ])

In [12]:
output_path = "Maze2.png"
matrix_to_image_GS(maze2, output_path)


In [13]:
image_name = os.path.splitext(os.path.basename(output_path))[0]
image_name

'Maze2'

In [14]:
try:
   os.makedirs(image_name)
except FileExistsError:
   # directory already exists
   pass

In [15]:
start = (1, 1)
end_point = (2, 5)

counter = 1
deep_path = []
final_path=[]
step(start[0],start[1], fn=image_name, matrix = maze2,deep_path = deep_path,final_path =final_path,  end_point = end_point)


This is the deep path: [(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (6, 2), (6, 3), (7, 3), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (7, 8), (7, 7), (7, 6), (7, 5), (7, 4), (6, 4), (6, 5), (6, 6), (5, 6), (5, 5), (5, 4), (5, 3), (4, 3), (4, 4), (4, 5), (4, 6), (3, 3), (2, 3), (1, 3), (6, 8), (5, 8), (4, 8), (3, 8), (2, 8), (2, 7), (2, 6), (2, 5)]


This is the final path: [(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (6, 2), (6, 3), (7, 3), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (7, 8), (6, 8), (5, 8), (4, 8), (3, 8), (2, 8), (2, 7), (2, 6), (2, 5)]


In [16]:
import warnings
warnings.simplefilter("ignore")

images = [imageio.imread(f'{image_name}/{i}.png') for i in range(2,counter+1)]
imageio.mimsave(f'{image_name}/path.gif', images, duration =5.5, loop=0)

In [17]:
def matrix_to_image(matrix, file_name = None):
    scale = 300 // matrix.shape[0]
    
    matrix = np.repeat(matrix, scale, axis=1)
    matrix = np.repeat(matrix, scale, axis=0)
    
    height, width = len(matrix), len(matrix[0])
    
    img = Image.new("RGB", (width, height))
    
    for y in range(height):
        for x in range(width):
            if matrix[y][x] == 1:
                img.putpixel((x,y), (0,0,0))
            elif matrix[y][x] == 0:
                img.putpixel((x,y), (255,255,255))
            elif matrix[y][x] == -2:
                img.putpixel((x,y), (0,0,255))
            
            else:
                img.putpixel((x,y),(0,255,0))
    
    img.save(f"{file_name}.png", quality=99)
    
matrix_to_image(image_to_matrix("Maze1.png"),'Maze1_resize')
matrix_to_image(image_to_matrix("Maze2.png"),'Maze2_resize')