# Numpy

In [1]:
import numpy as np

## Accessing elements

In [2]:
arr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [3]:
arr.shape

(9,)

In [4]:
arr.shape[0]

9

In [5]:
arr[2]

7

In [6]:
start = 1
end = 9
step = 2

# slicing
x = arr[start:end:step]
x

array([8, 6, 4, 2])

## 2D

In [7]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
len(arr2d)

3

In [9]:
arr2d[0]

array([1, 2, 3])

In [10]:
arr2d[0][0]

1

In [11]:
arr2d[0, 0]

1

In [12]:
arr2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [13]:
x = arr2d[:, 1:3]
x

array([[2, 3],
       [5, 6],
       [8, 9]])

In [14]:
arr2d.shape

(3, 3)

In [15]:
x.shape

(3, 2)

## 3D

In [16]:
arr = np.array([
                [[1, 2, 3],[4, 5, 6],[7, 8, 9]],
                [[10, 11, 12],[13, 14, 15],[16, 17, 18]],
                [[19, 20, 21],[22, 23, 24],[25, 26, 27]]
               ])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [17]:
arr.shape

(3, 3, 3)

In [18]:
arr.size

27

In [19]:
arr[1, 1:, 1:]

array([[14, 15],
       [17, 18]])

In [20]:
arr[::2, 1:, 1:]

array([[[ 5,  6],
        [ 8,  9]],

       [[23, 24],
        [26, 27]]])

In [21]:
arr.reshape((27,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [22]:
arr.reshape((3,9))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [23]:
arr.reshape((9,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [24]:
arr.reshape((3,10))

ValueError: cannot reshape array of size 27 into shape (3,10)

In [25]:
for x in arr:
    print(x)
    print("---")
    for y in x:
        print(y)
        print("====")
        for z in y:
            print(z)
            print("****")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[1 2 3]
====
1
****
2
****
3
****
[4 5 6]
====
4
****
5
****
6
****
[7 8 9]
====
7
****
8
****
9
****
[[10 11 12]
 [13 14 15]
 [16 17 18]]
---
[10 11 12]
====
10
****
11
****
12
****
[13 14 15]
====
13
****
14
****
15
****
[16 17 18]
====
16
****
17
****
18
****
[[19 20 21]
 [22 23 24]
 [25 26 27]]
---
[19 20 21]
====
19
****
20
****
21
****
[22 23 24]
====
22
****
23
****
24
****
[25 26 27]
====
25
****
26
****
27
****


## View vs Copy

In [26]:
arr2d = np.array([[9, 8, 7, 6], [5, 4, 3, 2]])
arr2d

array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [27]:
y = arr2d[:, 1:3].view() # Default
z = arr2d[:, 1:3].copy()
print("y:")
print(y)

print("")
print("z:")
print(z)

y:
[[8 7]
 [4 3]]

z:
[[8 7]
 [4 3]]


In [28]:
arr2d[0, 1] = 10
arr2d

array([[ 9, 10,  7,  6],
       [ 5,  4,  3,  2]])

In [29]:
y

array([[10,  7],
       [ 4,  3]])

In [30]:
z

array([[8, 7],
       [4, 3]])

### Deep Copy

In [1]:
import copy

lst_1 = [1, 2, [3, 4], 5]
lst_2 = copy.deepcopy(lst_1)
lst_2

[1, 2, [3, 4], 5]

In [2]:
lst_1[2][0] = 10
lst_1[1] = 15
lst_1

[1, 15, [10, 4], 5]

In [3]:
lst_2

[1, 2, [3, 4], 5]

## Iterating in Numpy

In [31]:
arr = np.array([[9, 8, 7, 6], [5, 4, 3, 2]])

In [32]:
for x in arr:
    for y in x:
        print(y)

9
8
7
6
5
4
3
2


In [33]:
arr = np.array([[[9, 8, 7, 6], [5, 4, 3, 2]], [[10, 11, 12, 13], [14, 15, 16, 17]]])
arr

array([[[ 9,  8,  7,  6],
        [ 5,  4,  3,  2]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

In [34]:
arr.shape

(2, 2, 4)

In [35]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

9
8
7
6
5
4
3
2
10
11
12
13
14
15
16
17
