# Finding Max

https://www.hackerrank.com/challenges/flipping-the-matrix/problem

In [52]:
import numpy as np

In [63]:
matrix = [[112, 42, 83, 119],
          [56, 125, 56, 49],
          [15, 78, 101, 43],
          [62, 98, 114, 108]]
matrix

[[112, 42, 83, 119], [56, 125, 56, 49], [15, 78, 101, 43], [62, 98, 114, 108]]

In [67]:
print(np.array(matrix))
print("")

mid_point = len(matrix) // 2

sum_value = 0
for x, row in enumerate(matrix[:mid_point]):
    for y, col in enumerate(row):
        if y < mid_point:
            m = len(matrix) - 1
            sum_value += max(matrix[x][y],
                           matrix[x][m-y],
                           matrix[m-x][y],
                           matrix[m-x][m-y])
sum_value

[[112  42  83 119]
 [ 56 125  56  49]
 [ 15  78 101  43]
 [ 62  98 114 108]]



414