# Numpy vs List

In [49]:
import numpy as np
import sys
import time

In [2]:
np.__version__

'1.23.5'

## List

In [8]:
# start with list

list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [4]:
# adding an integer to a list raises an exception

list2 = list1 + 10

TypeError: can only concatenate list (not "int") to list

In [10]:
# in order to add an integer to each item in the list,
# we should use a loop

list2 = []
for i in list1:
    list2.append(i + 10)
    
list2

[11, 12, 13, 14, 15]

In [5]:
# multiplying an integer to a list would duplicate the list

list2 = list1 * 2
list2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
# eventhough multipling will duplicate the list, division raises an error

list2 = list1 / 2
list2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [11]:
# again to multiply an integer to all the items of the list, we should use a loop

list2 = []
for i in list1:
    list2.append(i * 2)
    
list2

[2, 4, 6, 8, 10]

In [6]:
# multiplying two list raises an exception/error

list1 = [1, 2, 3, 4, 5]
list2 = [5, 4, 3, 2, 1]
list3 = list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

## Numpy

In [12]:
# initializing a numpy array

array1 = np.array([1, 2, 3, 4, 5])
type(array1)

numpy.ndarray

In [13]:
array1

array([1, 2, 3, 4, 5])

In [17]:
array1.shape

(5,)

In [18]:
# initializing a muli-dimensional array

n_array = np.array([(1, 2, 3),(4, 5, 6)])
# n_array = np.array([[1, 2, 3],[4, 5, 6]])
n_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
n_array.shape

(2, 3)

In [15]:
# getting access to an item in the 2nd row and 2nd column

n_array[1, 1]

# list1[1][1]

5

### Oprations on Numpy

In [19]:
array1 = np.array([1, 2, 3, 4, 5])

In [20]:
array2 = array1 + 10
array2

array([11, 12, 13, 14, 15])

In [21]:
array2 = array1 * 2
array2

array([ 2,  4,  6,  8, 10])

In [24]:
array2 = array1 / 2
array2

array([0.5, 1. , 1.5, 2. , 2.5])

In [22]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

array3 = array1 * array2
array3

array([5, 8, 9, 8, 5])

In [43]:
array1 = np.array([{"name":"DS"}, 2, [7, 9], 4.5, 5], dtype='object')

In [44]:
array1

array([{'name': 'DS'}, 2, list([7, 9]), 4.5, 5], dtype=object)

In [45]:
array1[0]

{'name': 'DS'}

In [46]:
array1[0]["name"]

'DS'

In [47]:
array1[2]

[7, 9]

### Numpy vs List: Memory Consumption

In [29]:
list1 = range(1000)

print(f"Size of each element of the list in bytes: {sys.getsizeof(list1)}")
print(f"Size of the whole list in bytes: {sys.getsizeof(list1) * len(list1)}")

Size of each element of the list in bytes: 48
Size of the whole list in bytes: 48000


In [32]:
array1 = np.arange(1000)

print(f"Size of each element of the list in bytes: {array1.itemsize}")
print(f"Size of the whole list in bytes: {array1.itemsize * array1.size}")

Size of each element of the list in bytes: 8
Size of the whole list in bytes: 8000


### Numpy vs List: Computational Time

In [56]:
size = 1000000

list1 = range(size)
list2 = range(size)

array1 = np.arange(size)
array2 = np.arange(size)

# unix timestamp in seconds
t0 = time.time()

# output = []
# for a, b in zip(list1, list2):
#     output.append(a * b)
    
output = [(a * b) for a, b in zip(list1, list2)]

t1 = time.time()

print(f"Time for LIST: {t1 - t0} seconds.")



# unix timestamp in seconds
t0 = time.time()

output = array1 * array2

t1 = time.time()

print(f"Time for Numpy: {t1 - t0} seconds.")


Time for LIST: 0.06617403030395508 seconds.
Time for Numpy: 0.007840156555175781 seconds.
