# Numpy

In [1]:
import numpy as np

## Accessing elements

In [2]:
arr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [3]:
arr.shape

(9,)

In [4]:
arr.shape[0]

9

In [5]:
arr[2]

7

In [9]:
start = 1
end = 9
step = 2

# slicing
x = arr[start:end:step]
x

array([8, 6, 4, 2])

In [11]:
arr2d = np.array([[9, 8, 7, 6], [5, 4, 3, 2]])
arr2d

array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [12]:
arr2d[0]

array([9, 8, 7, 6])

In [13]:
arr2d[0][0]

9

In [14]:
arr2d[0, 0]

9

In [25]:
arr2d[0:2, 1:3]

array([[8, 7],
       [4, 3]])

In [27]:
x = arr2d[:, 1:3]
x

array([[8, 7],
       [4, 3]])

In [29]:
arr2d.shape

(2, 4)

In [28]:
x.shape

(2, 2)

## View vs Copy

In [41]:
arr2d = np.array([[9, 8, 7, 6], [5, 4, 3, 2]])
arr2d

array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [43]:
y = arr2d[:, 1:3].view() # Default
z = arr2d[:, 1:3].copy()
print("y:")
print(y)

print("")
print("z:")
print(z)

y:
[[8 7]
 [4 3]]

z:
[[8 7]
 [4 3]]


In [38]:
arr2d[0, 1] = 10
arr2d

array([[ 9, 10,  7,  6],
       [ 5,  4,  3,  2]])

In [39]:
y

array([[10,  7],
       [ 4,  3]])

In [40]:
z

array([[8, 7],
       [4, 3]])

## Iterating in Numpy

In [45]:
arr = np.array([[9, 8, 7, 6], [5, 4, 3, 2]])

In [49]:
for x in arr:
    for y in x:
        print(y)

9
8
7
6
5
4
3
2


In [53]:
arr = np.array([[[9, 8, 7, 6], [5, 4, 3, 2]], [[10, 11, 12, 13], [14, 15, 16, 17]]])
arr

array([[[ 9,  8,  7,  6],
        [ 5,  4,  3,  2]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

In [54]:
arr.shape

(2, 2, 4)

In [55]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

9
8
7
6
5
4
3
2
10
11
12
13
14
15
16
17
