# Solving Maze

Reference:
https://levelup.gitconnected.com/an-animated-guide-to-implementing-dfs-in-python-to-find-a-path-1e939b7b8599

In [13]:
import numpy as np

In [14]:
maze = np.array([
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                ])
maze

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
start = (1, 1)
end = (2, 5)

marked_maze = maze.copy()
marked_maze[start] = 88
marked_maze[end] = 99
marked_maze

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, 88,  1,  0,  1,  0,  0,  0,  0,  1],
       [ 1,  0,  1,  0,  1, 99,  0,  0,  0,  1],
       [ 1,  0,  1,  0,  1,  1,  1,  1,  0,  1],
       [ 1,  0,  1,  0,  0,  0,  0,  1,  0,  1],
       [ 1,  0,  1,  0,  0,  0,  0,  1,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  1,  0,  1],
       [ 1,  0,  1,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  1,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

## Depth Frist Search

In [16]:
path_so_far = []
counter = 0

def make_step(i, j):
    global counter
    
    if i < 0 or j < 0 or i > len(maze)-1 or j > len(maze[0])-1:
        return
    if (i, j) in path_so_far or maze[i][j] > 0:
        return
    if maze[end[0]][end[1]] > 0:
        return
    
    path_so_far.append((i, j))
    counter += 1
    maze[i][j] = counter
    
    if (i, j) == (end[0], end[1]):
        print("Found!", path_so_far)
        path_so_far.pop()
        return
    else:
        make_step(i - 1, j)  # check top
        make_step(i + 1, j)  # check bottom
        make_step(i, j + 1)  # check right
        make_step(i, j - 1)  # check left
    path_so_far.pop()
    
    return

In [17]:
make_step(start[0], start[1])

Found! [(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (6, 2), (6, 3), (5, 3), (4, 3), (4, 4), (5, 4), (6, 4), (7, 4), (8, 4), (8, 5), (7, 5), (6, 5), (5, 5), (4, 5), (4, 6), (5, 6), (6, 6), (7, 6), (8, 6), (8, 7), (7, 7), (7, 8), (6, 8), (5, 8), (4, 8), (3, 8), (2, 8), (1, 8), (1, 7), (2, 7), (2, 6), (1, 6), (1, 5), (2, 5)]


In [18]:
maze

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1, 15,  1, 44, 43, 40, 39,  1],
       [ 1,  2,  1, 14,  1, 45, 42, 41, 38,  1],
       [ 1,  3,  1, 13,  1,  1,  1,  1, 37,  1],
       [ 1,  4,  1, 12, 16, 25, 26,  1, 36,  1],
       [ 1,  5,  1, 11, 17, 24, 27,  1, 35,  1],
       [ 1,  6,  9, 10, 18, 23, 28,  1, 34,  1],
       [ 1,  7,  1,  0, 19, 22, 29, 32, 33,  1],
       [ 1,  8,  1,  0, 20, 21, 30, 31,  0,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])